// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aegis/ent/atasklog"
	"aegis/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ATaskLogQuery is the builder for querying ATaskLog entities.
type ATaskLogQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ATaskLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ATaskLogQuery builder.
func (alq *ATaskLogQuery) Where(ps ...predicate.ATaskLog) *ATaskLogQuery {
	alq.predicates = append(alq.predicates, ps...)
	return alq
}

// Limit adds a limit step to the query.
func (alq *ATaskLogQuery) Limit(limit int) *ATaskLogQuery {
	alq.limit = &limit
	return alq
}

// Offset adds an offset step to the query.
func (alq *ATaskLogQuery) Offset(offset int) *ATaskLogQuery {
	alq.offset = &offset
	return alq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (alq *ATaskLogQuery) Unique(unique bool) *ATaskLogQuery {
	alq.unique = &unique
	return alq
}

// Order adds an order step to the query.
func (alq *ATaskLogQuery) Order(o ...OrderFunc) *ATaskLogQuery {
	alq.order = append(alq.order, o...)
	return alq
}

// First returns the first ATaskLog entity from the query.
// Returns a *NotFoundError when no ATaskLog was found.
func (alq *ATaskLogQuery) First(ctx context.Context) (*ATaskLog, error) {
	nodes, err := alq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{atasklog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (alq *ATaskLogQuery) FirstX(ctx context.Context) *ATaskLog {
	node, err := alq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ATaskLog ID from the query.
// Returns a *NotFoundError when no ATaskLog ID was found.
func (alq *ATaskLogQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = alq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{atasklog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (alq *ATaskLogQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := alq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ATaskLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ATaskLog entity is found.
// Returns a *NotFoundError when no ATaskLog entities are found.
func (alq *ATaskLogQuery) Only(ctx context.Context) (*ATaskLog, error) {
	nodes, err := alq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{atasklog.Label}
	default:
		return nil, &NotSingularError{atasklog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (alq *ATaskLogQuery) OnlyX(ctx context.Context) *ATaskLog {
	node, err := alq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ATaskLog ID in the query.
// Returns a *NotSingularError when more than one ATaskLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (alq *ATaskLogQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = alq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{atasklog.Label}
	default:
		err = &NotSingularError{atasklog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (alq *ATaskLogQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := alq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ATaskLogs.
func (alq *ATaskLogQuery) All(ctx context.Context) ([]*ATaskLog, error) {
	if err := alq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return alq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (alq *ATaskLogQuery) AllX(ctx context.Context) []*ATaskLog {
	nodes, err := alq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ATaskLog IDs.
func (alq *ATaskLogQuery) IDs(ctx context.Context) ([]uint64, error) {
	var ids []uint64
	if err := alq.Select(atasklog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (alq *ATaskLogQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := alq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (alq *ATaskLogQuery) Count(ctx context.Context) (int, error) {
	if err := alq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return alq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (alq *ATaskLogQuery) CountX(ctx context.Context) int {
	count, err := alq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (alq *ATaskLogQuery) Exist(ctx context.Context) (bool, error) {
	if err := alq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return alq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (alq *ATaskLogQuery) ExistX(ctx context.Context) bool {
	exist, err := alq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ATaskLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (alq *ATaskLogQuery) Clone() *ATaskLogQuery {
	if alq == nil {
		return nil
	}
	return &ATaskLogQuery{
		config:     alq.config,
		limit:      alq.limit,
		offset:     alq.offset,
		order:      append([]OrderFunc{}, alq.order...),
		predicates: append([]predicate.ATaskLog{}, alq.predicates...),
		// clone intermediate query.
		sql:    alq.sql.Clone(),
		path:   alq.path,
		unique: alq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		QuestID uint64 `json:"quest_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ATaskLog.Query().
//		GroupBy(atasklog.FieldQuestID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (alq *ATaskLogQuery) GroupBy(field string, fields ...string) *ATaskLogGroupBy {
	grbuild := &ATaskLogGroupBy{config: alq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := alq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return alq.sqlQuery(ctx), nil
	}
	grbuild.label = atasklog.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		QuestID uint64 `json:"quest_id,omitempty"`
//	}
//
//	client.ATaskLog.Query().
//		Select(atasklog.FieldQuestID).
//		Scan(ctx, &v)
//
func (alq *ATaskLogQuery) Select(fields ...string) *ATaskLogSelect {
	alq.fields = append(alq.fields, fields...)
	selbuild := &ATaskLogSelect{ATaskLogQuery: alq}
	selbuild.label = atasklog.Label
	selbuild.flds, selbuild.scan = &alq.fields, selbuild.Scan
	return selbuild
}

func (alq *ATaskLogQuery) prepareQuery(ctx context.Context) error {
	for _, f := range alq.fields {
		if !atasklog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if alq.path != nil {
		prev, err := alq.path(ctx)
		if err != nil {
			return err
		}
		alq.sql = prev
	}
	return nil
}

func (alq *ATaskLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ATaskLog, error) {
	var (
		nodes = []*ATaskLog{}
		_spec = alq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*ATaskLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &ATaskLog{config: alq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, alq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (alq *ATaskLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := alq.querySpec()
	_spec.Node.Columns = alq.fields
	if len(alq.fields) > 0 {
		_spec.Unique = alq.unique != nil && *alq.unique
	}
	return sqlgraph.CountNodes(ctx, alq.driver, _spec)
}

func (alq *ATaskLogQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := alq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (alq *ATaskLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   atasklog.Table,
			Columns: atasklog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: atasklog.FieldID,
			},
		},
		From:   alq.sql,
		Unique: true,
	}
	if unique := alq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := alq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, atasklog.FieldID)
		for i := range fields {
			if fields[i] != atasklog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := alq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := alq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := alq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := alq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (alq *ATaskLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(alq.driver.Dialect())
	t1 := builder.Table(atasklog.Table)
	columns := alq.fields
	if len(columns) == 0 {
		columns = atasklog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if alq.sql != nil {
		selector = alq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if alq.unique != nil && *alq.unique {
		selector.Distinct()
	}
	for _, p := range alq.predicates {
		p(selector)
	}
	for _, p := range alq.order {
		p(selector)
	}
	if offset := alq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := alq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ATaskLogGroupBy is the group-by builder for ATaskLog entities.
type ATaskLogGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (algb *ATaskLogGroupBy) Aggregate(fns ...AggregateFunc) *ATaskLogGroupBy {
	algb.fns = append(algb.fns, fns...)
	return algb
}

// Scan applies the group-by query and scans the result into the given value.
func (algb *ATaskLogGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := algb.path(ctx)
	if err != nil {
		return err
	}
	algb.sql = query
	return algb.sqlScan(ctx, v)
}

func (algb *ATaskLogGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range algb.fields {
		if !atasklog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := algb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := algb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (algb *ATaskLogGroupBy) sqlQuery() *sql.Selector {
	selector := algb.sql.Select()
	aggregation := make([]string, 0, len(algb.fns))
	for _, fn := range algb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(algb.fields)+len(algb.fns))
		for _, f := range algb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(algb.fields...)...)
}

// ATaskLogSelect is the builder for selecting fields of ATaskLog entities.
type ATaskLogSelect struct {
	*ATaskLogQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (als *ATaskLogSelect) Scan(ctx context.Context, v interface{}) error {
	if err := als.prepareQuery(ctx); err != nil {
		return err
	}
	als.sql = als.ATaskLogQuery.sqlQuery(ctx)
	return als.sqlScan(ctx, v)
}

func (als *ATaskLogSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := als.sql.Query()
	if err := als.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
