// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"aegis/app/service-main/internal/biz"
	"aegis/app/service-main/internal/conf"
	"aegis/app/service-main/internal/data"
	"aegis/app/service-main/internal/server"
	"aegis/app/service-main/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	mainRepo := data.NewMainRepo(dataData)
	mainUseCase := biz.NewMainUseCase(mainRepo)
	mainService := service.NewMainService(mainUseCase, dataData)
	httpServer := server.NewHTTPServer(confServer, mainService, logger)
	grpcServer := server.NewGRPCServer(confServer, mainService, logger)
	app := newApp(httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
